---

# if {{ kubeconfig_path }} does not exist fail
- name: Check if kubeconfig exists
  stat:
    path: "{{ kubeconfig_path }}"
  register: kubeconfig_exists

# if kubeconfig_exists does not exist fail
- name: Fail if kubeconfig does not exist
  fail:
    msg: "Kubeconfig does not exist"
  when: not kubeconfig_exists.stat.exists

- name: Create ServiceAccount for Controller
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: "{{ aap_openshift_serviceaccount_name }}"
        namespace: "{{ aap_controller_namespace }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Create ClusterRoleBinding for Controller
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: "{{ aap_openshift_serviceaccount_name }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: cluster-admin
      subjects:
      - kind: ServiceAccount
        name: "{{ aap_openshift_serviceaccount_name }}"
        namespace: "{{ aap_controller_namespace }}"

- name: "Create Service Account Token for ServiceAccount"
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig_path }}"
    state: present
    definition:
      kind: Secret
      metadata:
        namespace: "{{ aap_controller_namespace }}"
        name: "{{ aap_openshift_serviceaccount_token_name }}"
        annotations:
          kubernetes.io/service-account.name: "{{ aap_openshift_serviceaccount_name }}"
      type: kubernetes.io/service-account-token

- name: "Obtain Token for ServiceAccount"
  kubernetes.core.k8s_info:
    kubeconfig: "{{ kubeconfig_path }}"
    kind: Secret
    name: "{{ aap_openshift_serviceaccount_token_name }}"
    namespace: "{{ aap_controller_namespace }}"
  register: configure_aap_aap_sa_token_result

- name: Set OpenShift AAP ServiceAccount Token
  ansible.builtin.set_fact:
    configure_aap_aap_ocp_sa_token: "{{ configure_aap_aap_sa_token_result.resources[0].data.token | b64decode }}"

   