---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Display IP address, machine name, and OS
      debug:
        msg: |
          The IP address of this host is {{ ansible_default_ipv4.address }}
          The machine name of this host is {{ ansible_hostname }}
          The operating system of this host is {{ ansible_os_family }}