---
- name: Deploy Collection
  hosts: eap-collection
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../vars/{{ provision_var_file | default('provision.yml') }}"

    - name: Deploy Collection
      ansible.builtin.include_role:
        name: deploy_collection
 
