- name: Deploy Collection
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../vars/{{ provision_var_file | default('provision.yml') }}"

    - name: Call task from role
      ansible.builtin.include_role:
        name: deploy_collection
      tags: configure-vm
 
