---
- name: Deploy collection
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Configure OpenShift
      ansible.builtin.include_role:
        name: deploy_collection
        tasks_from: configure-ocp.yml

    - name: K8s Discovery
      ansible.builtin.include_role:
        name: k8s_discovery

- name: EAP  
  hosts: eap
  tasks:
    - name: Configure VM
      ansible.builtin.include_role:
        name: redhat.eap.deploy_collection
        tasks_from: configure-vm.yml